
Módulo Gráfico
===============
== GraphicController

Entidades estão associados a Sprites
Face Direction:: characters e monstes tem sprites segundo a direção de seu último movimento.

Animations:: Animações são sequências de sprites que são exibidas.Eventos podem disparar animações
		
Walk animation:: Sprites são alternadas para dar impressão de caminhar. Aplicáveis a Character e Moster

Explosion:: Meio e fronteria de explosão - Uma explosão com força 1 (a última da propagação) tem sprite diferente. A sprite é rotacionada segundo a direção da propagação

Win:: comemoração. 

Destructin Animation:: Entidades seguintes entidades possuem animação quando são destruidas:
Characters, Monsters, Soft Blocks e Power Ups.
	
Invencible Filter :: Charactes e Monsters aparecem claros enquanto invencíveis. Alterna entre claro e normal a cada 3 turnos.
Bomb Pulse :: Time Bombs alternam entre 3 sprites (de tamanhos um pouco diferentes) enquanto estão contando o tempo antes de disparar explosão.


==Renderizando

== Maps
	Usaremos Maps para renderizar nosso cenários.

Properties::
Properties of maps, layers or objects are represented by MapProperties (source).


== Layers
Constituimos o nosso mapa de camadas. A primeira contem o fundo. A segunda contem os blocos. A terceira os personagens. 
A quarta podem ter elementos do cenário que são superiores, como cobertura. 

Layers within a map are ordered and indexed, starting by index 0. You can access the layers of a map like this:

MapLayer layer = map.getLayers().get(0);

You can also search a layer by name

MapLayer layer = map.getLayers().get("my-layer");

These getter methods will always return a MapLayer. Some layers may be specialized and offer more functionality, in which case you can simply cast:

TiledMapTileLayer tiledLayer = (TiledMapTileLayer)map.getLayers().get(0);

Layer attributes
String name = layer.getName();
float opacity = layer.getOpacity();
boolean isVisible = layer.isVisible();



