

= Orientação a Objetos

A orientação a objetos é um paradígma de programação. Um paradígma de programação 
é um estilo fundamental de estruturar um programa. Na Orientação a Objetos tentamos 
traduzir em código os objetos do mundo real e suas interações diretamente em código.
Também criamos entidades abstratas, como "MovementSystem", uma entidade que controla 
os movimentos dos personagens em um jogo.

Orientação a Objetos é útil porque ajuda a criar código que é manutenível,
compreensível, adaptável e extensível. 

Orientação a Objetos ajuda ainda a criar código reutilizável seguinto o princípio DRY 
(Don't Repeat Yourself): escreva o código uma vez e então reutilize ele ao invés de copiar 
e colar em diferentes pontos.

== Como Aplicar

Para aplicar a orientação a objetos em uma problema, primeiro tente descrevê-lo


Identifique na descrição as partes independêntes, que tem estado e comportamento.
 Estas partes são os primeiros candidatos a virarem objetos no jogo.


Podemos identificar no bomberman por exemplo o objeto Personagem (Em inglês Character):


Que estados um personagem pode ter:
	Nome
	Posição
	Velocidade

E comportamentos:
	Caminhar
	Soltar bombas


== Exemplo Adotado: Bomberman

Bomb
BombDropper
BombSystem


== Classe
Uma classe é o tipo de um objeto. Uma classe é constituída de atributos e métodos.

== Objetos
Um objeto é uma instancia de uma classe. Os objetos são criados enquanto executamos um pograma, através do operador new. 
Podemos ter diversas instâncias de uma mesma classe em memória, cada uma contendo valores diferentes em seus atributos. 
Por exemplo, no bomberman, diferentes persongens poderiam ter diferentes posições na tela.
O comportamento do objeto também pode variar de intância para instância de uma mesma classe se o estes
 dependerem do estado da classe. Por exemplo o método caminhar() poderia modificar mais ou menos a posição de um personagem
 dependendo do seu atributo velocidade.


== Atributos
Representam carterísticas ou o estados do objeto. São ou dados que um objeto armazena em memória em suas variáveis para acessos
futuros.


== Métodos
São comportamentos ou ações que um objeto pode desempenhar em um sistema. Frequentemento os métodos alteram o estado do objeto, 
ou seja, seus atributos.



== Associação

Objetos podem referenciar outros objetos. A referência pode representar um relacionamento entre eles.
Por exemplo, uma bomba pode referenciar quem a criou. 

Um objeto pode utilizar a referência a um outro objeto para chamar um comportamento deste.

Um objeto pode criar outros objetos. Ou receber a referência do objeto como parâmetro de um método.


== Interface

Interfaces são declarações do que uma classe pode fazer. Mas a interface não diz nada de 'como' ela irá fazer.
Uma interface pode ser implementada por qualquer classe, não pependendo de qual hierarquia esta herda.

Duas classes com comportamentos diferentes podem possuir interfaces iguais e uma terceira classe pode utilizar as duas 
sem conhecer as Implementações da classe, apenas suas interfaces:

Interface  MapElement {
  draw()
}
class Bomb implement MapElement {}

MapDrawer{
  for(element in elementsList()){
    element.draw();

  }
}

Outra forma de se pensar em interface é como um contrato entre quem utiliza uma classe e quem a implementa. 
Em um programa orientado a objetos devemos favorecer a utilização de interfaces pois assim poderemos trocar 
a implementação mantendo o serviço.


== Encapsulamento

== Polimorfismo

Com polimorfismo um código cliente pode utilizar uma interface sem conhecer sua implementação. 
O sistema do bomberman que trata de vida de colisão poderia tratar a colisão de diversos elementos do jogo
sem conhecer cada um deles, porque cada elemento possui um *placement* que é o que importa para o sistema de colisão.
O polimorfismo é a principal razão para a existência de interfaces em línguagens orientadas a objetos.

ExplodeSystem

	bombEndity.getPlacement()
	monsterEndity.getPlacement()


O polimorfismo permite o desenvolvedor criar componentes “plugáveis”. Por exemplo se todos os sistemas do jogo
implementam uma mesma interface e o game loop chama cada sistema uma vez por turno através desta interface, 
ao criar um novo sistema não precisamos modificar o game loop, apenas adicionar o no sistema a coleção de 
sistemas que são executados.

== Boas práticas de programação Orientada a Objetos

Programar para interface, não implementações


== Associação


== Método Main

Um programa Java inicia pela execução de uma método main:


== Classe

As classes são os tipos dos objetos. Classes são templates que descrevem quais estados e comportamentos os objetos de seu tipo podem ter. Todo o código que descreve um programa Java é escrito em Classes, ou seja as classes são unidades básicas de um software escrito em Java.


[source,java,numbered]
----
include::src\impl\java\br\unb\unbomber\entity\Blocks.java[]
----

Os dados são armazenados em atributos:

[source,java,numbered]
----
include::src\impl\java\br\unb\unbomber\entity\Blocks.java[]
----

O comportamento é dado por médodos:
[source,java,numbered]
----
include::src\impl\java\br\unb\unbomber\entity\Blocks.java[]
----

Classes são escritas em arquivos texto nomeados com o mesmo nome da classe e terminados em .java.

Classes abstratas são classes que não podem ser instanciadas diretamente e devem ser extendidas por outras classes. 
Classes concretas em oposição são classes que podem ser instanciadas.

== Pacotes
As classes residem em pacotes. Os pacotes são um recurso da linguagem Java para organizar programas. 
Pacotes são declarados convencionalmente em uma notação de domínio reverso e na primeira línha de código do programa.

== Import
Para compor um programa com diversas classes, umas devem referenciar as outras. 
Para utilizarmos classes que estão fora do pacote precisamos primeiro importar estas classes.


== Variáveis e Tipos
Variáveis são regiões na memória que se pode armazenar dados para utilização futura.
Cada variável possui um identificador e um tipo e devem ser inicializados antes de ser utilizados.

Os tipos em Java são divididos em primitivos e de referência.
Os tipos primitivos são:
boolean, byte, char, short, int, long, float and double.


Todos os outros tipos são tipos de referência.
Tipos primitivos armazenam seus dados de forma independente

[source,java,numbered]
----
int a = 3;
int b = a; // atribuição do valor de ~a a ~b

a = 4;

System.out.println(a);
System.out.println(b);

----


Em oposição, tipos de referência tem um comportamento diferente. 
Programadores C irão achar o comportamento familiar ao comportamento de ponteiros em C.

Classes em Java são tipos de referência. Podemos utilizar o operador new para criar novos Objetos a partir de uma classe.
Dizemos que cada Objeto é uma instancia de uma classe pois possui seus próprios valores de atribuitos. 
Em uma determinada partida de bomberman cada personagem seria representado por uma instancia da classe personagem, 
pois cada um poderia ter diferentes características, como posição e número de pontos ganhos.
 A classe é uma forma a partir da qual se criam objetos.


[source,java,numbered]
----
Integer a = new Integer(3);
Integer b = a; // atribuição da referência de ~a a ~b

a = 4; //modificando o objeto

System.out.println(a);
System.out.println(b);

----

== Métodos
Semelhante a funções em C, descrevem o comportamento de um Objeto. Um método é constituído de uma assinatura e de um corpo.
Na assinatura  temos o identificador do método, os seus parâmetros e seu tipo de retorno.

O Corpo é um bloco de código delimitado por {} que contém o cõdigo a ser executado com o método for chamado.

Um método pode ter ou não retorno. Quando o método não tem retorno ele seu tipo de retorno é void.


== Atributos
Atributos são as variáveis que são declaradas fora de métodos, seu escopo é toda a classe e podem ser referenciadas
em qualquer método. Muitas vezes atributos armazenam dados referentes a características da classe a que se refere. 
Por exemplo, uma classe personagem poderia ter um atributo velocidade que armazena a velocidade máxima que um personagem pode ter.
Os atributos muitas vezes modificam o comportamento de um objeto. 

[source,java,numbered]
----
include::src\impl\java\br\unb\unbomber\entity\Blocks.java[]
----

== Controle

=== Tipo e Operações Booleanas
Java possui um tipo boleano que pode ser true ou false. As seguintes operações são operações boleanas o que quer dizer 
que elas retornam um valor booleano true ou false.

Operadores Bin

[source,java,numbered]
----
int a = 3;
int b = 2;
boolean c = a > b; 
System.out.println(c);  //true
----

Standard algebraic
equality or relational
operator

Java equality
or relational
operator


Sample
Java
condition

Meaning of
Java condition
Equality operators

= == x == y x is equal to y
≠ != x != y x is not equal to y
Relational operators
> > x > y x is greater than y
< < x < y x is less than y
≥ >= x >= y x is greater than or equal to y
≤ <= x <= y x is less than or equal to y


=== Controle

Java possui decisões de controle semelhantes a C. Mas diferente de C java possui tipos boleanos{true, false} e não aceita 
inteiros em decisões de controle.


if/else
[source,java,numbered]
----

int a = 1;
if(a){} //isso não é possível em Java

if(a>3){} //isto é possível em Java

boolean a = true;
if(a){} //isto é possível em Java
----


=== while

=== for



== Herança
O objetivo da herança é favorecer o reúso de código. Com herança podemos extender o comportamento de determinadas 
classes sem ter que escrever uma nova.


// Exemplo de 


Bomb{
  explode(){ ...}
}

RemoteExplodedBomb extends Bomb{
  remoteExplode(){}

}

= Princípios de Um bom Desing OO

== Alta Coesão
Fazer uma coisa bem

== Baixo acoplamento

Divisão de responsabilidades
Favorecer a utilização de interfaces

Como aplicar no bomberman:
	personagem tem o gatilho da criação de uma bomba, mas não cuida de mais detalhes do que isso.

== Encapsulamento

Encapsulamento é o princípio de esconder os detalhes, isto é, a implementação (o funcionamento interno) de um objeto ou módulo 
é escondido do resto do programa. Encapsulamento ajuda a criar código com baixo acoplamento (desta forma, mais fácil de ser reutilizado). 
Quando você favorece a utilização de interfaces ao invés de implementação.

É favorecido quando utilizamos métodos getters e setters para acessar atributos de uma classe.




= Patterns

= Frameworks

== Padrôes de Programação


