Departamento de Ciência da Computação – Universidade de Brasília

Programação Sistemática – 2º/2014



Trabalho Prático – Bomberman - Iteração 1
=========================================

Prazo de entrega:: 14/10/2014

Iteração 1 - Descrição
-----------------------

Nesta iteração iremos desenvolver os módulos simuladores como descrito em link:modules_simulation.adoc
Cada grupo irá desenvolver um módulo como definido na aula do dia 18/09/2014.


Modularização
--------------

Nessa etapa será desenvolvido módulos simuladores. Estes módulos serão consituidos de:

* Components (dados das entidades do jogo)
* Systems (lógica e regras do jogo)
* Events (dados de eventos do jogo)
* Testes (testes unitários)

Seguindo a descrição do documento link:arquitetura.adoc


Observação:

Seja C ou Java, utilize os princípios de modularidade na criação dos módulos ou classes, definindos seus módulos de definição (interfaces), módulos de implementação (classe) e organizando suas compilações e lincagens de forma adequada via um único makefile. 

Na criação dos módulos, lembre-se de usar as diretivas de controle para evitar inclusões múltiplas e identificando também o servidor.


Parte Escrita
-------------

Deverão ser entregues em conjunto com os códigos fonte: 
um arquivo LEIAME.TXT contendo a explicação de como utilizar o(s) programa(s). 
Tantos arquivos RELATORIO-nome.TXT quantos forem os membros do grupo. O tema nome deve identificar o membro do grupo ao qual se refere o relatório. Estes arquivos devem conter uma tabela de registro de trabalho organizada como a seguir:

Data | Horas Trabalhadas | Tipo Tarefa | Descrição da Tarefa Realizada

Na descrição da tarefa redija uma explicação breve sobre o que o componente do grupo fez. Esta descrição deve estar de acordo com o Tipo Tarefa. Cada Tipo Tarefa identifica uma natureza de atividade que deverá ser discriminada explicitamente, mesmo que, durante uma mesma sessão de trabalho tenham sido realizadas diversas tarefas. Os tipos de tarefa são:

* Estudar
* Especificar os módulos
* Especificar as funções
* Revisar especificações
* Projetar
* Revisar projetos
* Codificar módulo
* Revisar código do módulo
* Redigir casos de teste
* Revisar casos de teste
* Realizar os testes
* Diagnosticar e corrigir os problemas encontrados

TIP: Preencha esta tabela de atividades ao longo do processo. *NÃO DEIXE PARA ÚLTIMA HORA, POIS VOCÊ NÃO SE LEMBRARÁ DO QUE FEZ TAL DIA, TAL HORA*. Com relatórios similares a esse você aprende a planejar o seu trabalho.

EXCELENTE TRABALHO! 